[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
headless = false
address = "localhost"
port = 8501

[theme]
base = "light"
primaryColor = "#1f6f5b"
backgroundColor = "#f7f4ef"
secondaryBackgroundColor = "#fffdfb"
textColor = "#1f1a17"
font = "sans serif"
